#!/usr/bin/env node
"use strict";

// Hard timeout — must finish within 5s
const TIMEOUT = setTimeout(() => process.exit(0), 5000);
TIMEOUT.unref();

const fs = require("fs");
const path = require("path");
const os = require("os");
const { loadState, saveState, updateStreak } = require("../lib/state");
const { getEvolutionProgress } = require("../lib/jelly");
const { renderBanner } = require("../lib/display");

// ── Statusline auto-setup ──────────────────────────────
// On first run, wire up jelly-pet's statusline.js into
// Claude Code's settings.json so the pet shows in the bar.
function setupStatusline() {
  const pluginDir = process.env.PLUGIN_DIR || path.resolve(__dirname, "..");
  const statuslineJs = path.join(pluginDir, "lib", "statusline.js");
  if (!fs.existsSync(statuslineJs)) return;

  const jellyDir = path.join(os.homedir(), ".jelly-pet");
  const markerPath = path.join(jellyDir, ".statusline-path");

  // Skip if already configured with this exact plugin path
  try {
    if (fs.existsSync(markerPath) && fs.readFileSync(markerPath, "utf-8").trim() === pluginDir) return;
  } catch (e) {}

  // Write wrapper script to ~/.jelly-pet/statusline-command.sh
  const wrapperPath = path.join(jellyDir, "statusline-command.sh");
  const wrapper = [
    "#!/bin/sh",
    "# Jelly Pet statusline (auto-generated by jelly-pet plugin)",
    `cat | node "${statuslineJs}" 2>/dev/null || {`,
    '  input=$(cat)',
    '  model=$(echo "$input" | jq -r \'.model.display_name // "Unknown"\')',
    '  printf "%s\\n" "$model"',
    "}",
    ""
  ].join("\n");

  fs.mkdirSync(jellyDir, { recursive: true });
  fs.writeFileSync(wrapperPath, wrapper, { mode: 0o755 });

  // Update ~/.claude/settings.json
  const settingsPath = path.join(os.homedir(), ".claude", "settings.json");
  try {
    let settings = {};
    if (fs.existsSync(settingsPath)) {
      settings = JSON.parse(fs.readFileSync(settingsPath, "utf-8"));
    }

    // Already pointing to jelly-pet? Skip.
    if (settings.statusLine && settings.statusLine.command &&
        settings.statusLine.command.includes("jelly-pet")) {
      fs.writeFileSync(markerPath, pluginDir);
      return;
    }

    // Back up previous statusline config
    if (settings.statusLine) {
      settings._statusLineBackup = JSON.parse(JSON.stringify(settings.statusLine));
    }

    settings.statusLine = {
      type: "command",
      command: `sh "${wrapperPath}"`
    };

    fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2));
    fs.writeFileSync(markerPath, pluginDir);
  } catch (e) {
    // Silent fail — don't break Claude Code
  }
}

// ── Main ───────────────────────────────────────────────
function main() {
  setupStatusline();

  let state = loadState();

  // First run — no pet selected yet
  if (!state.pet) {
    console.log("\n  🍬 Jelly Pet에 오신 걸 환영해요!");
    console.log("  /jelly-pet:switch 명령으로 펫을 선택하고 이름을 지어주세요.");
    console.log("  선택 가능: cat, dog, hamster, rabbit, hedgehog\n");
    return;
  }

  // Update streak
  state = updateStreak(state);
  saveState(state);

  // Render banner
  const evoProgress = getEvolutionProgress(state.jelly);
  console.log(renderBanner(state, evoProgress));
}

try {
  main();
} catch (err) {
  // Silent fail — don't break Claude Code
}
