#!/usr/bin/env node
"use strict";

// Hard timeout — must finish within 5s
const TIMEOUT = setTimeout(() => process.exit(0), 5000);
TIMEOUT.unref();

const fs = require("fs");
const path = require("path");
const os = require("os");
const { loadState, saveState, updateStreak } = require("../lib/state");
const { getEvolutionProgress } = require("../lib/jelly");
const { renderBanner } = require("../lib/display");

// ── Auto-setup ─────────────────────────────────────────
// On first run, wire up jelly-pet into Claude Code's settings.json:
// 1. Statusline — pet ASCII art in the status bar
// 2. Stop hook — jelly collection on every assistant turn (like report-usage.js)
function setupPlugin() {
  const pluginDir = process.env.PLUGIN_DIR || path.resolve(__dirname, "..");
  const statuslineJs = path.join(pluginDir, "lib", "statusline.js");
  const collectorJs = path.join(pluginDir, "lib", "jelly-collector.js");

  const jellyDir = path.join(os.homedir(), ".jelly-pet");
  const markerPath = path.join(jellyDir, ".setup-version");
  const SETUP_VERSION = "2"; // bump to re-run setup

  // Skip if already configured with this version
  try {
    if (fs.existsSync(markerPath) && fs.readFileSync(markerPath, "utf-8").trim() === SETUP_VERSION) return;
  } catch (e) {}

  fs.mkdirSync(jellyDir, { recursive: true });

  // Write statusline wrapper script
  const wrapperPath = path.join(jellyDir, "statusline-command.sh");
  if (fs.existsSync(statuslineJs)) {
    const wrapper = [
      "#!/bin/sh",
      "# Jelly Pet statusline (auto-generated by jelly-pet plugin)",
      `cat | node "${statuslineJs}" 2>/dev/null || {`,
      '  input=$(cat)',
      '  model=$(echo "$input" | jq -r \'.model.display_name // "Unknown"\')',
      '  printf "%s\\n" "$model"',
      "}",
      ""
    ].join("\n");
    fs.writeFileSync(wrapperPath, wrapper, { mode: 0o755 });
  }

  // Update ~/.claude/settings.json
  const settingsPath = path.join(os.homedir(), ".claude", "settings.json");
  try {
    let settings = {};
    if (fs.existsSync(settingsPath)) {
      settings = JSON.parse(fs.readFileSync(settingsPath, "utf-8"));
    }

    let changed = false;

    // ── Statusline setup ──
    if (fs.existsSync(statuslineJs) &&
        !(settings.statusLine && settings.statusLine.command &&
          settings.statusLine.command.includes("jelly-pet"))) {
      if (settings.statusLine) {
        settings._statusLineBackup = JSON.parse(JSON.stringify(settings.statusLine));
      }
      settings.statusLine = { type: "command", command: `sh "${wrapperPath}"` };
      changed = true;
    }

    // ── Stop hook for jelly collection ──
    if (fs.existsSync(collectorJs)) {
      if (!settings.hooks) settings.hooks = {};
      if (!settings.hooks.Stop) settings.hooks.Stop = [];

      const jellyHookCmd = `node "${collectorJs}"`;
      const alreadyRegistered = settings.hooks.Stop.some(entry =>
        entry.hooks && entry.hooks.some(h => h.command && h.command.includes("jelly-collector"))
      );

      if (!alreadyRegistered) {
        settings.hooks.Stop.push({
          matcher: ".*",
          hooks: [{
            type: "command",
            command: jellyHookCmd,
            timeout: 5000
          }]
        });
        changed = true;
      }
    }

    if (changed) {
      fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2));
    }
    fs.writeFileSync(markerPath, SETUP_VERSION);
  } catch (e) {
    // Silent fail — don't break Claude Code
  }
}

// ── Main ───────────────────────────────────────────────
function main() {
  setupPlugin();

  let state = loadState();

  // First run — no pet selected yet
  if (!state.pet) {
    console.log("\n  🍬 Jelly Pet에 오신 걸 환영해요!");
    console.log("  /jelly-pet:switch 명령으로 펫을 선택하고 이름을 지어주세요.");
    console.log("  선택 가능: cat, dog, hamster, rabbit, hedgehog\n");
    return;
  }

  // Update streak
  state = updateStreak(state);
  saveState(state);

  // Render banner
  const evoProgress = getEvolutionProgress(state.jelly);
  console.log(renderBanner(state, evoProgress));
}

try {
  main();
} catch (err) {
  // Silent fail — don't break Claude Code
}
